### ISSUE TITLE
Stack overflow error

### ISSUE THREAD

**Issue by SoullessShadow** [Ovydux/MC-Startup-Script#8]
Hi,

Using the flags on the modpack: MineColonies Dimmensional Adventure
Causes the server to spit a error for stackoverflow.
I've attached a log for you to have a look but something with the Graalvm tags cause this to happen
[latest (1).log](https://github.com/Obydux/Minecraft-GraalVM-Flags/files/14393288/latest.1.log)

**Comment by SoullessShadow** [comment]
Removing -Dgraal.TuneInlinerExploration=1 -Dgraal.LoopRotation=true -Dgraal.OptWriteMotion=true makes the server launch fine, so one of these arguments are flagging, so might be worth noting as this may affect other modpacks

**Comment by Obydux** [comment]
Could you figure out which one of those flags is causing it?

**Comment by mythiccal** [comment]
> Could you figure out which one of those flags is causing it?

Had this issue myself - it's an issue with using Community Edition instead of Enterprise Edition with Java 17 (didn't test with 21).
The offending flags are `-Dgraal.TuneInlinerExploration=1 -Dgraal.LoopRotation=true -Dgraal.OptWriteMotion=true -Dgraal.CompilerConfiguration=enterprise`, all 4 must be removed for it to boot using these flags.

**Comment by Obydux** [comment]
I'd suggest using the Enterprise Edition. By itself it's slightly faster than the CE and these flags you're removing are in a way important. These days installing EE is pretty straight forward if you're using [SDKMAN](https://sdkman.io/), it's just a single command.
